import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import HomeSection from '../components/HomeSection'
import HomeCategory from '../components/HomeCategory'
import { Fade } from "react-reveal"

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>Apple (United Kingdom)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="max-w-[2500px] w-full mx-auto">
        <HomeSection 
          title="iPhone 12" 
          image="https://www.apple.com/euro/home/q/screens_alt/images/heroes/iphone-12/iphone_12_updated__jepm2xpxncuy_largetall.jpg" 
          color="black" 
        />
        <Fade left>
          <HomeSection 
            title="iPhone 12 pro" 
            image="https://www.apple.com/v/home/aa/images/heroes/iphone-12-pro/iphone_12_pro_us__e5oyysg4k0ya_largetall.jpg" 
          />
        </Fade>
      
        <Fade right>
          <HomeSection 
            title="iPad pro" 
            image="https://www.apple.com/v/home/aa/images/heroes/ipad-pro/hero_ipad_pro__gl982dtu49im_largetall.jpg" 
          />
        </Fade>

        <div className="md:grid grid-flow-row-dense grid-cols-2 bg-white p-5 -mt-2">
          <HomeCategory 
            title="iOS 15"
            subtitle="In touch. In the moment."
            imageUrl="https://www.apple.com/v/home/aa/images/promos/ios-15-preview/tile_ios15__fdoo7kck6322_small_2x.jpg"
          />
          <HomeCategory 
            title="International Collection"
            subtitle="There's a strap for every fan."
            imageUrl="https://www.apple.com/euro/home/r/screens_alt/images/promos/watch-international-collection/promo_watch_international_collection__doumy2y89m4i_small_2x.jpg"
          />
          <HomeCategory 
            title="iPadOS 15"
            subtitle="Work wonders. With ease."
            imageUrl="https://www.apple.com/v/home/aa/images/promos/ipados-15-preview/promo_ipados__fhorzbh9xz2i_small_2x.jpg"
          />
          <HomeCategory 
            title="macOS Monterey"
            subtitle='High powers meets "High everyone".'
            imageUrl="https://www.apple.com/v/home/aa/images/promos/macos-monterey-preview/promo_macos_monterey__cn85xkubs58i_small_2x.jpg"
          />
          <HomeCategory 
            title="Music"
            subtitle="Introducing Spatial Audio with Dolby Atmos"
            imageUrl="https://www.apple.com/v/home/aa/images/promos/apple-music-spatial-audio/promo_spatial_audio_taylor_swift__d0ewry6j28qe_small_2x.jpg"
            light
          />
          <HomeCategory 
            title="tv+"
            subtitle="Based on the award-winning novels by Isaac Asimov."
            imageUrl="https://www.apple.com/v/home/aa/images/promos/tv-plus-foundation/promo_foundation__fsmifbfgugia_small_2x.jpg"
            light
          />
        </div>
      </div>
      
      

    </div>
  )
}